-- 3세대 대장균의 ID 출력 SQL
-- 대장균 ID에 대해 오름차순 정렬

SELECT ed1.ID
FROM ECOLI_DATA as ed1 
JOIN ECOLI_DATA as ed2 ON ed1.PARENT_ID = ed2.ID 
JOIN ECOLI_DATA as ed3 ON (ed2.PARENT_ID = ed3.ID)
WHERE ed2.PARENT_ID IS NOT NULL AND ed3.PARENT_ID IS NULL
ORDER BY ed1.ID ASC