-- 입양 간 동물 중, 보호기간이 가장 길었던 
-- 2마리의 아이디와 이름을 조회
-- 결과 보호기간 순 DESC
WITH RANKED as (
    SELECT AI.ANIMAL_ID as ANIMAL_ID, AI.NAME as NAME ,
    ROW_NUMBER() OVER (ORDER BY DATEDIFF(AO.DATETIME, AI.DATETIME) DESC) as RN
    FROM ANIMAL_INS as AI JOIN ANIMAL_OUTS as AO
    ON AI.ANIMAL_ID = AO.ANIMAL_ID
)

SELECT ANIMAL_ID, NAME
FROM RANKED
WHERE RN <= 2
ORDER BY RN;
    