-- 대장균 개체의 크기를 내림차순으로 정렬했을 때
-- 상위 %로 나누어서 분류
-- ID, COLONY_NAME 출력
-- ID 오름차순으로 정렬
WITH RANKED AS (
    SELECT 
    ID,
    SIZE_OF_COLONY,
    ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RN,
    COUNT(*) OVER() AS TOTAL_COUNT
    FROM ECOLI_DATA
    ORDER BY SIZE_OF_COLONY DESC
)

SELECT ID, 
    CASE
    WHEN
    RN <= TOTAL_COUNT *0.25 THEN 'CRITICAL'
    WHEN
    RN > TOTAL_COUNT*0.25 AND RN <= TOTAL_COUNT * 0.5 THEN 'HIGH'
    WHEN
    RN > TOTAL_COUNT * 0.5 AND RN <= TOTAL_COUNT * 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
    END as COLONY_NAME
FROM RANKED
ORDER BY ID ASC