-- 종류별 물고기 이름과 잡은 수 출력

SELECT COUNT(FI.FISH_TYPE) as FISH_COUNT,
FN.FISH_NAME AS FISH_NAME
FROM FISH_INFO AS FI 
JOIN FISH_NAME_INFO AS FN
ON FI.FISH_TYPE = FN.FISH_TYPE
GROUP BY FI.FISH_TYPE, FN.FISH_NAME
ORDER BY FISH_COUNT DESC