-- 각 세대별 자식이 없는 개체의 수,
-- 세대를 출력하는 SQL문..
-- 세대에 대해서 오름차순
WITH RECURSIVE CTE AS (
  -- 1세대: 부모가 없는 (PARENT_ID IS NULL) 대장균
  SELECT 
    ID,
    1 AS GENERATION
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NULL

  UNION ALL

  -- 그 자식들: 부모 + 1세대씩 세대 올림
  SELECT 
    E.ID,
    CTE.GENERATION + 1
  FROM ECOLI_DATA E
  JOIN CTE ON E.PARENT_ID = CTE.ID
)

SELECT 
 COUNT(*) AS COUNT,
  CTE.GENERATION
FROM CTE
LEFT JOIN ECOLI_DATA AS E2 ON CTE.ID = E2.PARENT_ID
WHERE E2.PARENT_ID IS NULL  -- 자식이 없는 대장균만
GROUP BY CTE.GENERATION
ORDER BY CTE.GENERATION ASC;