-- 100이하 LOW, 1000이하 MEDIUM, 1000초과 HIGH
-- id, size 출력
-- id 오름차순
SELECT ID, 
CASE 
    WHEN
    SIZE_OF_COLONY <= 100 THEN 'LOW'
    WHEN
    SIZE_OF_COLONY > 100 AND SIZE_OF_COLONY <=1000 THEN 'MEDIUM'
    ELSE 'HIGH'
END AS SIZE
FROM ECOLI_DATA