-- 코드를 입력하세요
-- 9~19:59까지 각 시간대별 입양 몇건 발생?
-- DATETIME = 날짜 + 시간 = YYYY-MM-DD HH:MM:SS 형식
SELECT HOUR(DATETIME) as HOUR, count(*) as count
FROM ANIMAL_OUTS
WHERE TIME(DATETIME) BETWEEN '09:00:00' AND '19:59:59'
GROUP BY HOUR(DATETIME)
ORDER BY HOUR ASC
