-- PRODUCT 테이블에 카테고리 코드 앞자리 2자리 별
-- 상품 개수 출력
-- 상품 카테고리 코드 기준 오름차순 정렬
WITH CATEGORYS as (
    SELECT PRODUCT_ID, SUBSTRING(PRODUCT_CODE, 1,2) as CATEGORY
    FROM PRODUCT
)

SELECT CATEGORY, COUNT(CATEGORY) as PRODUCTS
FROM CATEGORYS
GROUP BY CATEGORY
HAVING CATEGORY IS NOT NULL
ORDER BY CATEGORY asc

