WITH MAX_COLONY AS(
SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, (MAX(SIZE_OF_COLONY)) as MAX_SIZE
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT MC.YEAR as YEAR, (MC.MAX_SIZE - ED.SIZE_OF_COLONY) as YEAR_DEV, ED.ID
FROM ECOLI_DATA as ED
JOIN MAX_COLONY as MC
on YEAR(ED.DIFFERENTIATION_DATE) = MC.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC