-- 총 주문량 3000보다 높으면서 주성분 과일인 아이스크림 맛
-- 총주문량 DESC 조회

SELECT FLAVOR
FROM FIRST_HALF
WHERE TOTAL_ORDER > 3000 AND
FLAVOR IN (
    SELECT FLAVOR
    FROM ICECREAM_INFO
    WHERE INGREDIENT_TYPE = 'fruit_based'
) 
ORDER BY TOTAL_ORDER DESC
