-- 종류별 가장 큰 물고기의 Id, 이름, 길이 출력
-- 물고기 id에 대한 asc

SELECT FI.ID, FN.FISH_NAME as FISH_NAME, FI.LENGTH
FROM FISH_INFO as FI JOIN FISH_NAME_INFO as FN
ON FI.FISH_TYPE = FN.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) as MAX_LEN
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS MAX_INFO 
ON FI.FISH_TYPE = MAX_INFO.FISH_TYPE AND FI.LENGTH = MAX_INFO.MAX_LEN
ORDER BY FI.ID ASC