-- 거래상태가 SALE이면 판매중,
-- RESERVED면 예약중, DONE이면 거래완료로 분류
-- 게시글 ID기준 내림차순
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, 
CASE 
    WHEN STATUS = 'SALE' THEN '판매중'
    WHEN STATUS = 'RESERVED' THEN '예약중'
    ELSE '거래완료'
END as STATUS 
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = '2022-10-05'
ORDER BY BOARD_ID DESC