WITH FRONT AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
PYTHON AS (
    SELECT CODE AS CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
),
CSH AS (
    SELECT CODE AS CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
)


SELECT CASE
        WHEN FRONT.CODE & SKILL_CODE AND PYTHON.CODE & SKILL_CODE THEN 'A'
        WHEN CSH.CODE & SKILL_CODE THEN 'B'
        WHEN FRONT.CODE & SKILL_CODE THEN 'C' 
        END as GRADE,
        ID, EMAIL
FROM DEVELOPERS, FRONT, PYTHON, CSH
HAVING GRADE IS NOT NULL 
ORDER BY GRADE, ID